- platform: template
  switches:
    abode_alarm_home:
      friendly_name: 'Abode Armed Home'
      value_template: "{% if is_state('alarm_control_panel.abode_alarm', 'disarmed') %}off{% else %}on{% endif %}"
      turn_on:
        service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.abode_alarm
      turn_off:
        service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.abode_alarm
