- platform: template
  switches:
    watch_tv:
      friendly_name: 'Watch TV'
      value_template: "{% if is_state('sensor.living_room_tv', 'WatchTV') %}on{% else %}off{% endif %}"
      turn_on:
        service: remote.turn_on
        data_template:
          entity_id: remote.living_room
          activity: 24508505
      turn_off:
        service: remote.turn_off
        entity_id: remote.living_room
    apple_tv:
      friendly_name: 'Watch AppleTV'
      value_template: "{% if is_state('sensor.living_room_tv', 'Watch AppleTV') %}on{% else %}off{% endif %}"
      turn_on:
        service: remote.turn_on
        data_template:
          entity_id: remote.living_room
          activity: 21876818
      turn_off:
        service: remote.turn_off
        entity_id: remote.living_room
    ps4:
      friendly_name: 'PS4'
      value_template: "{% if is_state('sensor.living_room_tv', 'PS4') %}on{% else %}off{% endif %}"
      turn_on:
        service: remote.turn_on
        data_template:
          entity_id: remote.living_room
          activity: 21916668
      turn_off:
        service: remote.turn_off
        entity_id: remote.living_room
    nintendo_switch:
      friendly_name: 'Nintendo Switch'
      value_template: "{% if is_state('sensor.living_room_tv', 'Switch') %}on{% else %}off{% endif %}"
      turn_on:
        service: remote.turn_on
        data_template:
          entity_id: remote.living_room
          activity: 25260577
      turn_off:
        service: remote.turn_off
        entity_id: remote.living_room