# Based on: https://github.com/happyleavesaoc/my-home-automation/tree/master/homeassistant
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: !secret unit_system
  time_zone: !secret timezone
  customize: !include includes/customize.yaml
  customize_glob: !include includes/customize_pattern.yaml
  packages:  !include_dir_named packages
  
#google:
#  client_id: !secret google_client_id
#  client_secret: !secret google_client_secret
  
ecobee:
  api_key: !secret ecobee_api_key
  
ifttt:
  key: !secret ifttt_api_key

digital_ocean:
  access_token: !secret digitalocean_api_key
  
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  username: !secret mqtt_username
  password: !secret mqtt_password
  
blink:
  username: !secret blink_username
  password: !secret blink_password

abode:
  username: !secret abode_username
  password: !secret abode_password

skybell:
  username: !secret skybell_username
  password: !secret skybell_password

usps:
  username: !secret usps_username
  password: !secret usps_password

hue:
  bridges:
    - host: !secret hue_host
      allow_in_emulated_hue: false
      allow_unreachable: true
      allow_hue_groups: false
  
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml
  
emulated_hue:
  expose_by_default: false

http:
  base_url: !secret hass_base_url
  server_port: !secret hass_server_port
  api_password: !secret hass_api_password
  ssl_certificate: !secret hass_ssl_certificate
  ssl_key: !secret hass_ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 3

automation: !include_dir_merge_list automations
binary_sensor: !include_dir_merge_list binary_sensors
camera: !include_dir_merge_list cameras
cover: !include_dir_merge_list covers
device_tracker: !include includes/device_tracker.yaml
group: !include_dir_merge_named groups
history: !include includes/history.yaml
input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
light: !include_dir_merge_list lights
logger: !include includes/logger.yaml
logbook: !include includes/logbook.yaml
notify: !include includes/notify.yaml
recorder: !include includes/recorder.yaml
remote: !include_dir_merge_list remotes
scene: !include_dir_merge_list scenes
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
zone: !include includes/zones.yaml

ios:
sun:
frontend:
config: