- alias: Notification - Wife Arrives Home
  trigger:
    - platform: state
      entity_id: input_select.sara_status_dropdown
      from: 'Away'
      to: 'Just Arrived'
      
  condition:
    - condition: state
      entity_id: switch.tracking_alerts
      state: 'on'
      
  action:
    - service: notify.him
      data:
        message: >
          Your wife has arrived home!

- alias: Notification - Wife Leaves Home
  trigger:
    - platform: state
      entity_id: input_select.sara_status_dropdown
      to: 'Just Left'
      
  condition:
    - condition: state
      entity_id: switch.tracking_alerts
      state: 'on'
      
  action:
    - service: notify.him
      data:
        message: >
          Your wife has left home!
        
- alias: Notification - Wife Arrives At Work
  trigger:
    - platform: state
      entity_id: !secret her_device_tracker
      from: 'not_home'
      to: !secret her_work_name
      
  condition:
    - condition: state
      entity_id: switch.tracking_alerts
      state: 'on'
      
  action:
    - service: notify.him
      data:
        message: >
          Your wife has arrived at work safe and sound!
          
- alias: Notification - Wife Leaves Work For Home
  trigger:
    - platform: state
      entity_id: !secret her_device_tracker
      from: !secret her_work_name
      to: 'not_home'
      
  condition:
    - condition: state
      entity_id: switch.tracking_alerts
      state: 'on'
      
    - condition: time
      after: '14:00:00'
      before: '16:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      
  action:
    - service: notify.him
      data:
        message: >
          Your wife has left work and will be home in {{ states.sensor.her_evening.state }} minutes!