- alias: Notification - Husband arrives home
  trigger:
    - platform: state
      entity_id: !secret his_device_tracker
      from: 'not_home'
      to: 'home'
      
  condition:
    - condition: state
      entity_id: switch.tracking_alerts
      state: 'on'
      
  action:
    - service: notify.her
      data:
        message: >
          Your husband has arrived home!

- alias: Notification - Husband leaves home
  trigger:
    - platform: state
      entity_id: !secret his_device_tracker
      from: 'home'
      to: 'not_home'
      
  condition:
    - condition: state
      entity_id: switch.tracking_alerts
      state: 'on'
      
  action:
    - service: notify.her
      data:
        message: >
          Your husband has left home!
        
- alias: Notification - Husband arrives at work
  trigger:
    - platform: state
      entity_id: !secret his_device_tracker
      from: 'not_home'
      to: !secret his_work_name
      
  condition:
    - condition: state
      entity_id: switch.tracking_alerts
      state: 'on'
      
  action:
    - service: notify.her
      data:
        message: >
          Your husband has arrived at work safe and sound!
          
- alias: Notification - Husband leaves work to probably go home
  trigger:
    - platform: state
      entity_id: !secret his_device_tracker
      from: !secret his_work_name
      to: 'not_home'
      
  condition:
    - condition: state
      entity_id: switch.tracking_alerts
      state: 'on'
      
    - condition: time
      after: '15:00:00'
      before: '17:30:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      
  action:
    - service: notify.her
      data:
        message: >
          Your husband has left work and will be home in {{ states.sensor.his_evening.state }} minutes!