- alias: Trigger - Flip Internet Down Boolean
  trigger:
    - platform: state
      entity_id: sensor.internet
      from: 'up'
      to: 'down'
      for:
        minutes: 5
    
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.internet

- alias: Notify & Trigger - Internet Back Online
  trigger:
    - platform: state
      entity_id: sensor.internet
      from: 'down'
      to: 'up'
      
  condition:
    - condition: state
      entity_id: input_boolean.internet
      state: 'off'
    
  action:
    - service: notify.him
      data:
        message: >
          The internet was down and is now back online!
          
    - service: input_boolean.turn_on
      entity_id: input_boolean.internet