- alias: Flip mqtt variable switch if internet goes down
  trigger:
    - platform: state
      entity_id: sensor.internet
      from: 'up'
      to: 'down'
      for:
        minutes: 5
    
  action:
    - service: switch.turn_on
      entity_id: switch.internet_down

- alias: Notify him on internet coming back up
  trigger:
    - platform: state
      entity_id: sensor.internet
      from: 'down'
      to: 'up'
      
  condition:
    - condition: state
      entity_id: switch.internet_down
      state: 'on'
    
  action:
    - service: notify.him
      data:
        message: >
          The internet was down and is now back online!
          
    - service: switch.turn_off
      entity_id: switch.internet_down