- alias: Notification - Home-Assistant Start
  trigger:
    - platform: homeassistant
      event: start
      
  action:
    - service: notify.him
      data:
        message: >
          Home-Assistant has started!