# Issue exists preventing this from firing: https://github.com/home-assistant/home-assistant/issues/7058

- alias: Notify him on HASS startup
  trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.him
    data:
      message: "Home Assistant has started!"