- alias: Notification - Water Sensors
  trigger:
    - platform: state
      entity_id: group.water_sensors
      from: 'off'
      to: 'on'

  action:
    - service: notify.all
      data_template:
        message: 'The {{ trigger.from_state.attributes.friendly_name }} water sensor has triggered!'