- alias: Notification - Water Sensors
  trigger:
    - platform: state
      entity_id: binary_sensor.water_leak_sensor_158d0001bbe989, binary_sensor.water_leak_sensor_158d0001c32b43
      from: 'off'
      to: 'on'

  action:
    - service: notify.all
      data_template:
        message: 'The {{ trigger.from_state.attributes.friendly_name }} water sensor has triggered!'