- platform: command_line
  name: New Commits
  scan_interval: 600
  command: "git fetch && git log master..origin/master --pretty=oneline | wc -l"

# Note: This will not work until the given automation also works
#- platform: template
#  sensors:
#    home_assistant_last_restart:
#      value_template: '{{ as_timestamp(states.automation.notify_him_on_hass_startup.attributes.last_triggered)  | timestamp_custom("%Y-%m-%d %H:%M:%S") }}'
#      friendly_name: Last Restart

- platform: command_line
  name: "HASS Uptime"
  command: echo "$(($(date +%s) - $(date -d "$(head -n1 home-assistant.log | cut -d' ' -f-2)" +%s)))"
  scan_interval: 720
  value_template: >-
    {% set uptime = value | int %}
    {% set seconds = uptime % 60 %}
    {% set minutes = ((uptime % 3600) / 60) | int %}
    {% set hours = ((uptime % 86400) / 3600) | int %}
    {% set days = (uptime / 86400) | int %}
    {%- if days > 0 -%}
      {%- if days == 1 -%}
        1 day
      {%- else -%}
        {{ days }} days
      {%- endif -%}
      {{ ', ' }}
    {%- endif -%}
    {{ '%02d' % hours }}:{{ '%02d' % minutes }}