- platform: command_line
  name: New Commits
  scan_interval: 600
  command: "cd ~/.homeassistant/ && git fetch && git log master..origin/master --pretty=oneline | wc -l"

# Note: This will not work until the given automation also works
- platform: template
  sensors:
    home_assistant_last_restart:
      value_template: '{{ as_timestamp(states.automation.notify_him_on_hass_startup.attributes.last_triggered)  | timestamp_custom("%Y-%m-%d %H:%M:%S") }}'
      friendly_name: Last Restart