- platform: nzbget
  host: !secret nzbget_host
  username: !secret nzbget_username
  password: !secret nzbget_password
  monitored_variables:
    - average_download_rate
    - download_rate
    - download_size
    - free_disk_space
    - remaining_size
    - uptime
    - article_cache