- platform: systemmonitor
  resources:
  - type: memory_use_percent
  - type: processor_use
  - type: since_last_boot
  - type: network_in
    arg: eth0
  - type: network_out
    arg: eth0
  - type: ipv4_address
    arg: eth0
