# Harmony-API (https://github.com/maddox/harmony-api)
#
# Uses Harmony-API to monitor the on/off state of
# the home theater.

- platform: template
  sensors:
    home_theater:
      value_template: "{% if is_state('sensor.living_room_tv', 'PowerOff') %}off{% else %}on{% endif %}"
