# Harmony-API (https://github.com/maddox/harmony-api)
#
# Uses Harmony-API to monitor the on/off state of
# the home theater.

- platform: mqtt
  name: "Home Theater"
  state_topic: "home/harmony/state"
  payload_on: "on"
  payload_off: "off"
