- platform: template
  sensors:
    hvac_status:
      friendly_name: HVAC Status
      value_template: "{{ states.climate.downstairs.attributes.operation != 'idle' or states.climate.upstairs.attributes.operation != 'idle' }}"
