- alias: Commute delay - her evening
  trigger:
    platform: numeric_state
    entity_id: sensor.her_evening
    above: 20
  condition:
    - condition: time
      after: '13:30:00'
      before: '16:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: switch.her_alert_delays
      state: 'on'
    - condition: state
      entity_id: !secret her_device_tracker
      state: !secret her_work_name
  action:
    service: notify.her
    data:
      message: >
        Commute to home delay of {{ trigger.to_state.state|round }} minutes