- alias: Commute delay - his morning
  trigger:
    platform: numeric_state
    entity_id: sensor.his_morning
    above: 40
  condition:
    - condition: time
      after: '06:30:00'
      before: '09:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: switch.his_alert_delays
      state: 'on'
    - condition: state
      entity_id: !secret his_device_tracker
      state: 'home'
  action:
    service: notify.him
    data:
      message: >
        Commute to work delay of {{ trigger.to_state.state|round }} minutes