- alias: Notification - Husband morning commute
  trigger:
    platform: numeric_state
    entity_id: sensor.his_morning
    above: 35
  condition:
    - condition: time
      after: '06:30:00'
      before: '09:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: switch.his_alert_delays
      state: 'on'
    - condition: state
      entity_id: input_select.wil_status_dropdown
      state: 'Home'
  action:
    service: notify.him
    data:
      message: >
        Commute to work delay of {{ trigger.to_state.state|round }} minutes

- alias: Notification - Wife evening commute
  trigger:
    platform: numeric_state
    entity_id: sensor.his_evening
    above: 35
  condition:
    - condition: time
      after: '15:30:00'
      before: '17:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: switch.his_alert_delays
      state: 'on'
    - condition: or
      conditions:
        - condition: state
          entity_id: !secret his_device_tracker
          state: !secret his_work_name
        - condition: state
          entity_id: !secret his_device_tracker
          state: !secret his_work_name
  action:
    service: notify.him
    data:
      message: >
        Commute to home delay of {{ trigger.to_state.state|round }} minutes