- alias: Notification - Wife morning commute
  trigger:
    platform: numeric_state
    entity_id: sensor.her_evening
    above: 20
  condition:
    - condition: time
      after: '06:30:00'
      before: '07:30:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: switch.her_alert_delays
      state: 'on'
    - condition: state
      entity_id: !secret her_device_tracker
      state: 'home'
  action:
    service: notify.her
    data:
      message: >
        Commute to work delay of {{ trigger.to_state.state|round }} minutes

- alias: Notification - Wife evening commute
  trigger:
    platform: numeric_state
    entity_id: sensor.her_evening
    above: 20
  condition:
    - condition: time
      after: '13:30:00'
      before: '16:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: switch.her_alert_delays
      state: 'on'
    - condition: or
      conditions:
        - condition: state
          entity_id: !secret her_device_tracker
          state: 'not_home'
        - condition: state
          entity_id: !secret her_device_tracker
          state: !secret her_work_name
  action:
    service: notify.her
    data:
      message: >
        Commute to home delay of {{ trigger.to_state.state|round }} minutes