- alias: Presence - When everyone leaves turn everything off

  trigger:
    - platform: state
      entity_id: group.all_home
      to: 'not_home'
      
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
      
    - condition: state
      entity_id: switch.presence
      state: 'on'
      
    - condition: state
      entity_id: switch.vacation
      state: 'off'
      
    - condition: state
      entity_id: switch.guests
      state: 'off'
      
  action:
    - service: light.turn_off
      entity_id: group.indoor_lights
      
    - service: remote.turn_off
      entity_id: remote.living_room