- alias: Blink - When the alarm is set to away arm all Blink cameras

  trigger:
    - platform: state
      entity_id: alarm_control_panel.abode_alarm
      to: 'armed_away'
      
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
      
    - condition: state
      entity_id: switch.presence
      state: 'on'
      
    - condition: state
      entity_id: switch.vacation
      state: 'off'
      
    - condition: state
      entity_id: switch.guests
      state: 'off'
      
  action:
    - service: blink.arm_system
      data:
        device_armed: 'True'

- alias: Blink - When the alarm is set to home arm all outdoor Blink cameras

  trigger:
    - platform: state
      entity_id: alarm_control_panel.abode_alarm
      to: 'armed_away'
      
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
      
    - condition: state
      entity_id: switch.presence
      state: 'on'
      
    - condition: state
      entity_id: switch.vacation
      state: 'off'
      
    - condition: state
      entity_id: switch.guests
      state: 'off'
      
  action:
  - service: blink.arm_camera
      data_template:
        friendly_name: "{{ states.camera.backyard.attributes.friendly_name }}"
        
- alias: Blink - When the alarm is set to standby disarm all blink cameras

  trigger:
    - platform: state
      entity_id: alarm_control_panel.abode_alarm
      to: 'disarmed'
      from: 'armed_away'
      
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
      
    - condition: state
      entity_id: switch.presence
      state: 'on'
      
    - condition: state
      entity_id: switch.vacation
      state: 'off'
      
    - condition: state
      entity_id: switch.guests
      state: 'off'
      
  action:
    - service: blink.arm_system
      data:
        device_armed: 'False'
        
- alias: Blink - Update Blink pictures every day at noon

  trigger:
    - platform: time
      at: '12:00:00'
      
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
      
    - condition: state
      entity_id: switch.guests
      state: 'off'
      
  action:
    - service: blink.snap_picture
      data_template:
        friendly_name: "{{ states.camera.loft.attributes.friendly_name }}"
        
    - delay: 00:00:15
          
    - service: blink.snap_picture
      data_template:
        friendly_name: "{{ states.camera.downstairs.attributes.friendly_name }}"
        
    - delay: 00:00:15
          
    - service: blink.snap_picture
      data_template:
        friendly_name: "{{ states.camera.backyard.attributes.friendly_name }}"
        
    - delay: 00:00:15
          
    - service: blink.snap_picture
      data_template:
        friendly_name: "{{ states.camera.master_bedroom.attributes.friendly_name }}"
        
    - delay: 00:00:15
          
    - service: blink.snap_picture
      data_template:
        friendly_name: "{{ states.camera.molly_cam.attributes.friendly_name }}"