- alias: Arm the Blink system when the alarm is in away mode

  trigger:
    - platform: state
      entity_id: alarm_control_panel.abode_alarm
      to: 'away'
      
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
      
    - condition: state
      entity_id: switch.presence
      state: 'on'
      
    - condition: state
      entity_id: switch.vacation
      state: 'off'
      
    - condition: state
      entity_id: switch.guests
      state: 'off'
      
  action:
    - service: blink.arm_system
      data:
        device_armed: 'True'
        
- alias: Disarm the Blink system when the alarm is disarmed

  trigger:
    - platform: state
      entity_id: alarm_control_panel.abode_alarm
      to: 'disarmed'
      from: 'away'
      
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
      
    - condition: state
      entity_id: switch.presence
      state: 'on'
      
    - condition: state
      entity_id: switch.vacation
      state: 'off'
      
    - condition: state
      entity_id: switch.guests
      state: 'off'
      
  action:
    - service: blink.arm_system
      data:
        device_armed: 'False'
        
- alias: Update pictures once a day at noon

  trigger:
    - platform: time
      at: '12:00:00'
      
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
      
    - condition: state
      entity_id: switch.guests
      state: 'off'
      
  action:
    - service: blink.snap_picture
      data_template:
        friendly_name: "{{ states.camera.loft.attributes.friendly_name }}"
        
    - delay: 00:00:15
          
    - service: blink.snap_picture
      data_template:
        friendly_name: "{{ states.camera.downstairs.attributes.friendly_name }}"
        
    - delay: 00:00:15
          
    - service: blink.snap_picture
      data_template:
        friendly_name: "{{ states.camera.backyard.attributes.friendly_name }}"
        
    - delay: 00:00:15
          
    - service: blink.snap_picture
      data_template:
        friendly_name: "{{ states.camera.master_bedroom.attributes.friendly_name }}"
        
    - delay: 00:00:15
          
    - service: blink.snap_picture
      data_template:
        friendly_name: "{{ states.camera.closet.attributes.friendly_name }}"