- alias: Blink - Alarm Away Arm All Cameras

  trigger:
    - platform: state
      entity_id: alarm_control_panel.abode_alarm
      to: 'armed_away'
      
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
      
    - condition: state
      entity_id: switch.presence
      state: 'on'
      
    - condition: state
      entity_id: switch.vacation
      state: 'off'
      
    - condition: state
      entity_id: switch.guests
      state: 'off'
      
  action:
    - service: blink.arm_camera
      data_template:
        friendly_name: "{{ states.camera.backyard.attributes.friendly_name }}"
        device_armed: 'True'
    - service: blink.arm_camera
      data_template:
        friendly_name: "{{ states.camera.loft.attributes.friendly_name }}"
        device_armed: 'True'
    - service: blink.arm_camera
      data_template:
        friendly_name: "{{ states.camera.master_bedroom.attributes.friendly_name }}"
        device_armed: 'True'
    - service: blink.arm_camera
      data_template:
        friendly_name: "{{ states.camera.downstairs.attributes.friendly_name }}"
        device_armed: 'True'
    - service: blink.arm_camera
      data_template:
        friendly_name: "{{ states.camera.molly_cam.attributes.friendly_name }}"
        device_armed: 'True'
    - service: blink.arm_system
      data:
        device_armed: 'True'

- alias: Blink - Alarm Home Arm Outdoor Cameras

  trigger:
    - platform: state
      entity_id: alarm_control_panel.abode_alarm
      to: 'armed_home'
      
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
      
    - condition: state
      entity_id: switch.presence
      state: 'on'
      
    - condition: state
      entity_id: switch.vacation
      state: 'off'
      
    - condition: state
      entity_id: switch.guests
      state: 'off'
      
  action:
    - service: blink.arm_camera
      data_template:
        friendly_name: "{{ states.camera.backyard.attributes.friendly_name }}"
        device_armed: 'True'
    - service: blink.arm_camera
      data_template:
        friendly_name: "{{ states.camera.loft.attributes.friendly_name }}"
        device_armed: 'False'
    - service: blink.arm_camera
      data_template:
        friendly_name: "{{ states.camera.master_bedroom.attributes.friendly_name }}"
        device_armed: 'False'
    - service: blink.arm_camera
      data_template:
        friendly_name: "{{ states.camera.downstairs.attributes.friendly_name }}"
        device_armed: 'False'
    - service: blink.arm_camera
      data_template:
        friendly_name: "{{ states.camera.molly_cam.attributes.friendly_name }}"
        device_armed: 'False'
    - service: blink.arm_system
      data:
        device_armed: 'True'
        
- alias: Blink - Alarm Standby Disarm All Cameras

  trigger:
    - platform: state
      entity_id: alarm_control_panel.abode_alarm
      to: 'disarmed'
      from: 'armed_away'
      
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
      
    - condition: state
      entity_id: switch.presence
      state: 'on'
      
    - condition: state
      entity_id: switch.vacation
      state: 'off'
      
    - condition: state
      entity_id: switch.guests
      state: 'off'
      
  action:
    - service: blink.arm_system
      data:
        device_armed: 'False'
    - service: blink.arm_camera
      data_template:
        friendly_name: "{{ states.camera.backyard.attributes.friendly_name }}"
        device_armed: 'True'
    - service: blink.arm_camera
      data_template:
        friendly_name: "{{ states.camera.loft.attributes.friendly_name }}"
        device_armed: 'True'
    - service: blink.arm_camera
      data_template:
        friendly_name: "{{ states.camera.master_bedroom.attributes.friendly_name }}"
        device_armed: 'True'
    - service: blink.arm_camera
      data_template:
        friendly_name: "{{ states.camera.downstairs.attributes.friendly_name }}"
        device_armed: 'True'
        
- alias: Blink - Blink Snapshots At Noon

  trigger:
    - platform: time
      at: '12:00:00'
      
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
      
    - condition: state
      entity_id: switch.guests
      state: 'off'
      
  action:
    - service: blink.snap_picture
      data_template:
        friendly_name: "{{ states.camera.loft.attributes.friendly_name }}"
        
    - delay: 00:00:15
          
    - service: blink.snap_picture
      data_template:
        friendly_name: "{{ states.camera.downstairs.attributes.friendly_name }}"
        
    - delay: 00:00:15
          
    - service: blink.snap_picture
      data_template:
        friendly_name: "{{ states.camera.backyard.attributes.friendly_name }}"
        
    - delay: 00:00:15
          
    - service: blink.snap_picture
      data_template:
        friendly_name: "{{ states.camera.master_bedroom.attributes.friendly_name }}"
        
    - delay: 00:00:15
          
    - service: blink.snap_picture
      data_template:
        friendly_name: "{{ states.camera.molly_cam.attributes.friendly_name }}"