- alias: Presence - Close garage door if it is left open

  trigger:
    - platform: state
      entity_id: group.all_devices
      to: 'not_home'
      
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
      
    - condition: state
      entity_id: switch.presence
      state: 'on'
      
    - condition: state
      entity_id: switch.guests
      state: 'off'
      
    - condition: state
      entity_id: cover.garage_door
      state: 'open'
      
  action:
    - service: notify.all
      data:
        message: >
          The garage door was left open but it has now been closed.
      
    - service: cover.close_cover
      entity_id: cover.garage_door