- alias: Presence - Close garage door if everyone gone and it is left open

  trigger:
    - platform: state
      entity_id: input_select.wil_status_dropdown
      to: 'Away'
    - platform: state
      entity_id: input_select.sara_status_dropdown
      to: 'Away'
      
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
      
    - condition: state
      entity_id: switch.presence
      state: 'on'
      
    - condition: state
      entity_id: switch.guests
      state: 'off'
      
    - condition: state
      entity_id: cover.garage_door
      state: 'open'

    - condition: state
      entity_id: input_select.wil_status_dropdown
      state: 'Away'

    - condition: state
      entity_id: input_select.sara_status_dropdown
      state: 'Away'
      
  action:
    - service: cover.close_cover
      entity_id: cover.garage_door
      
    - service: notify.all
      data:
        message: >
          The garage door was left open but it has now been closed.