- alias: Lights - Turn some lights on if it gets dark out
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 20.0
      
    - platform: numeric_state
      entity_id: sensor.dark_sky_cloud_coverage
      above: 90
      
    - platform: numeric_state
      entity_id: sensor.dark_sky_precip_intensity
      above: 1

  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: numeric_state
                entity_id: sun.sun
                value_template: '{{ state.attributes.elevation }}'
                below: 20.0
              - condition: numeric_state
                entity_id: sensor.dark_sky_cloud_coverage
                above: 90
          - condition: numeric_state
            entity_id: sensor.dark_sky_precip_intensity
            above: 1
            
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'
        
      - condition: state
        entity_id: switch.automation
        state: 'on'
        
      - condition: state
        entity_id: switch.presence
        state: 'on'
        
      - condition: state
        entity_id: switch.vacation
        state: 'off'
        
      - condition: state
        entity_id: group.all_home
        state: 'home'
        
  action:
    - service: light.turn_on
      entity_id:
        - light.living_room
      data:
        brightness: 255