- alias: Trigger - Turn off all the indoor lights and media center and arm alarm to home mode
  trigger:
    - platform: state
      entity_id: input_boolean.good_night
      to: 'on'
      from: 'off'

  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
      
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.good_night
      
    - service: light.turn_off
      entity_id: group.all_lights

    - service: remote.turn_off
      entity_id: remote.living_room

    - service: alarm_control_panel.alarm_arm_home
      entity_id: alarm_control_panel.abode_alarm