- alias: Lights - Turn the TV backlight on when the theater is turned on

  trigger:
    - platform: state
      entity_id: remote.living_room
      from: 'off'
      to: 'on'
    
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
      
  action:
    - service: scene.turn_on
      entity_id: scene.theater_on