- alias: Lights - Turn the TV backlight off when the theater is turned off

  trigger:
    - platform: state
      entity_id: remote.living_room
      from: 'on'
      to: 'off'
      
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
      
  action:
    - service: scene.turn_on
      entity_id: scene.theater_off
