#  Note that `group.all_devices` is special: Its state
#  is 'home' if ANY tracked device is home, and 'not_home'
#  if EVERY tracked device is not home.

- alias: Turn on lights when someone gets home within an hour of sunset

    trigger:
      - platform: state
        entity_id: group.all_devices
        state: 'home'
      
    condition:
      - condition: state
        entity_id: switch.automation
        state: 'on'
        
      - condition: state
        entity_id: switch.presence
        state: 'on'

      - condition: sun
        after: sunset
        after_offset: '-00:59:00'

  action:
    - service: scene.turn_on
      entity_id: scene.indoor_lights_home
