- alias: Lights - Front Door Motion Lights On
  trigger:
    - platform: state
      entity_id: binary_sensor.skybell_front_door_motion
      to: 'on'

  action:
    - service: script.front_door_motion