# Sometimes I turn this off and forget to turn it back on
- alias: Skybell - Motion Detection On At Sunset

  trigger:
    - platform: sun
      event: 'sunset'
      
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
      
    - condition: state
      entity_id: switch.skybell_front_door_motion_sensor
      state: 'off'
      
  action:
    - service: switch.turn_on
      entity_id: switch.skybell_front_door_motion_sensor

- alias: Skybell - Motion Detection On When Alarm Armed

  trigger:
    - platform: state
      entity_id: alarm_control_panel.abode_alarm
      from: 'disarmed'
      
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
      
    - condition: state
      entity_id: switch.skybell_front_door_motion_sensor
      state: 'off'
      
  action:
    - service: switch.turn_on
      entity_id: switch.skybell_front_door_motion_sensor