- alias: Turn off Outdoor Lights at Sunset

  trigger:
    - platform: sun
      event: 'sunrise'
      offset: '-00:30:00'
        
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
        
  action:
    - service: scene.turn_on
      entity_id: scene.outdoor_lights_sunrise