- alias: Lights - No Motion Late Night Lights Off

  trigger:
    - platform: sun
      event: 'sunrise'
      offset: '-03:00:00'
        
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
    
    - condition: state
      entity_id: binary_sensor.loft_occupancy
      state: 'off'

    - condition: state
      entity_id: binary_sensor.bedroom_occupancy
      state: 'off'

    - condition: state
      entity_id: binary_sensor.upstairs_occupancy
      state: 'off'

    - condition: state
      entity_id: binary_sensor.downstairs_occupancy
      state: 'off'
        
  action:
    - delay: '00:{{ (range(1, 59)|random|int) }}:00'
    - service: light.turn_off
      entity_id: group.indoor_lights

- alias: Lights - Outdoor Lights Off 15m Before Sunrise

  trigger:
    - platform: sun
      event: 'sunrise'
      offset: '-00:15:00'
        
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
        
  action:
    - service: light.turn_off
      entity_id: group.outdoor_lights