- alias: Turn off Lights at Sunrise

  trigger:
    - platform: sun
      event: 'sunrise'
      offset: '-02:00:00'
        
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
        
  action:
    - delay: '00:{{ (range(1, 55)|random|int) }}:00'
    - service: light.turn_off
      entity_id: group.all_lights