- alias: Lights - Turn off any indoor lights if nobody is moving around 2-3 hours before sunrise

  trigger:
    - platform: sun
      event: 'sunrise'
      offset: '-03:00:00'
        
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
    
    - condition: state
      entity_id: binary_sensor.loft_occupancy
      state: 'off'

    - condition: state
      entity_id: binary_sensor.bedroom_occupancy
      state: 'off'

    - condition: state
      entity_id: binary_sensor.upstairs_occupancy
      state: 'off'

    - condition: state
      entity_id: binary_sensor.downstairs_occupancy
      state: 'off'
        
  action:
    - delay: '00:{{ (range(1, 59)|random|int) }}:00'
    - service: light.turn_off
      entity_id: group.indoor_lights

- alias: Lights - Turn off outdoor lights half an hour before sunrise

  trigger:
    - platform: sun
      event: 'sunrise'
      offset: '-00:30:00'
        
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
        
  action:
    - service: light.turn_off
      entity_id: group.outdoor_lights