- alias: Presence & Lights - Turn on indoor lights an hour before sunset if somebody is home

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:59:00'
        
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
        
    - condition: state
      entity_id: switch.presence
      state: 'on'
        
    - condition: state
      entity_id: switch.vacation
      state: 'off'
        
    - condition: or
      conditions:
        - condition: state
          entity_id: input_select.wil_status_dropdown
          state: 'Home'

        - condition: state
          entity_id: input_select.sara_status_dropdown
          state: 'Home'
        
  action:
    - service: scene.turn_on
      entity_id: scene.indoor_lights_sunset

- alias: Lights - Turn on outdoor lights at sunset

  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
        
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
        
  action:
    - service: script.monthly_color_scene