- alias: Vacation & Lights - Turn off lights randomly between 9pm and 12am

  trigger:
    - platform: time
      at: '21:00:00'
        
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
        
    - condition: state
      entity_id: switch.vacation
      state: 'on'
        
  action:
    - delay: '{{ ((range(1, 2) | random) | int) ~ ":" ~ ((range(1, 59) | random) | int)  ~ ":" ~  ((range(1, 59) | random) | int) }}'
    
    - service: scene.turn_off
      entity_id: scene.vacation
