- alias: Turn on lights an hour before sunset with a random delay from 1 hour 1 minute to 2 hours 59 minutes

    trigger:
      - platform: sun
        event: 'sunset'
        offset: '-00:59:00'
        
    condition:
      - condition: state
        entity_id: switch.automation
        state: 'on'
        
      - condition: state
        entity_id: switch.vacation
        state: 'on'
        
  action:
    - delay: '{{ (range(1, 2)|random|int) }}:{{ (range(1, 59)|random|int) }}:00'
    
    - service: scene.turn_on
      entity_id: scene.vacation
