- alias: Turn off lights at 10pm with a random delay of up to 1hr59m59s

  trigger:
    - platform: time
      after: '22:00:00'
        
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
        
    - condition: state
      entity_id: switch.vacation
      state: 'on'
        
  action:
    - delay: '{{ ((range(0, 1) | random) | int) ~ ":" ~ ((range(1, 59) | random) | int)  ~ ":" ~  ((range(1, 59) | random) | int) }}'
    
    - service: scene.turn_off
      entity_id: scene.indoor_lights_sunset
