- alias: Vacation & Lights - Turn on lights randomly around sunset

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:59:00'
        
  condition:
    - condition: state
      entity_id: switch.automation
      state: 'on'
        
    - condition: state
      entity_id: switch.vacation
      state: 'on'
        
  action:
    - delay: '{{ ((range(1, 2) | random) | int) ~ ":" ~ ((range(1, 59) | random) | int)  ~ ":" ~  ((range(1, 59) | random) | int) }}'
    
    - service: scene.turn_on
      entity_id: scene.vacation