- platform: owntracks
  max_gps_accuracy: 200
  track_new_devices: False
  
- platform: asuswrt
  host: 192.168.1.1
  protocol: telnet
  mode: router
  username: !secret asuswrt_username
  password: !secret asuswrt_password
  track_new_devices: False