- platform: bluetooth_tracker
  interval_seconds: 10
  consider_home: 120
  track_new_devices: no

- platform: icloud
  username: !secret his_icloud_username
  password: !secret his_icloud_password
#  account_name: wils_iphone_icloud
  
#- platform: icloud
#  username: !secret her_icloud_username
#  password: !secret her_icloud_password
#  account_name: saras_iphone_icloud