#- platform: owntracks_http
#  max_gps_accuracy: 100
#  track_new_devices: yes
  
- platform: asuswrt
  host: 192.168.1.1
  protocol: telnet
  mode: router
  username: !secret asuswrt_username
  password: !secret asuswrt_password
  track_new_devices: yes
  
- platform: bluetooth_tracker
  interval_seconds: 10
  consider_home: 120
  track_new_devices: yes